"use client";

import { useState } from 'react';
import { Sparkles, Loader2, ChevronRight, BrainCircuit, MessageSquareQuote, ShieldCheck } from 'lucide-react';
import { getAiExecutiveSummary } from '@/lib/actions';
import { AppStats } from '@/lib/db-clients';

export function AISummary({ apps }: { apps: AppStats[] }) {
    const [summary, setSummary] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);

    const generateSummary = async () => {
        setIsLoading(true);
        try {
            const result = await getAiExecutiveSummary(apps);
            setSummary(result);
        } catch (error) {
            setSummary("Failed to generate summary. Please try again later.");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="bg-zinc-900/40 border border-zinc-800/60 rounded-3xl overflow-hidden backdrop-blur-md shadow-2xl transition-all hover:border-blue-500/30">
            <div className="p-8">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8">
                    <div className="flex items-start gap-4">
                        <div className="p-3 bg-blue-500/10 rounded-2xl border border-blue-500/20 text-blue-400">
                            <BrainCircuit className="w-6 h-6" />
                        </div>
                        <div>
                            <h3 className="text-xl font-black text-white tracking-tight flex items-center gap-2">
                                AI Executive Summary
                                <Sparkles className="w-4 h-4 text-amber-400 animate-pulse" />
                            </h3>
                            <p className="text-sm text-zinc-500 font-medium">Global portfolio analysis & actionable recommendations.</p>
                        </div>
                    </div>
                    
                    {!summary && !isLoading && (
                        <button 
                            onClick={generateSummary}
                            className="group flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-2xl font-bold text-sm shadow-lg shadow-blue-500/20 hover:shadow-blue-500/40 hover:-translate-y-0.5 transition-all active:scale-95"
                        >
                            <Sparkles className="w-4 h-4 group-hover:rotate-12 transition-transform" />
                            Generate Report
                            <ChevronRight className="w-4 h-4 opacity-50 group-hover:translate-x-1 transition-transform" />
                        </button>
                    )}
                </div>

                {isLoading && (
                    <div className="flex flex-col items-center justify-center py-12 gap-4">
                        <div className="relative">
                            <div className="absolute inset-0 bg-blue-500/20 blur-2xl rounded-full" />
                            <Loader2 className="w-10 h-10 text-blue-500 animate-spin relative z-10" />
                        </div>
                        <div className="text-center">
                            <p className="text-sm font-bold text-white mb-1">Analyzing Company Data...</p>
                            <p className="text-xs text-zinc-500">Gemini 1.5 is scanning financials and activity logs.</p>
                        </div>
                    </div>
                )}

                {summary && !isLoading && (
                    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                        <div className="bg-black/40 border border-zinc-800/50 rounded-2xl p-6 relative group">
                            <div className="absolute -top-3 -right-3 p-2 bg-emerald-500/10 border border-emerald-500/20 rounded-lg backdrop-blur-md">
                                <ShieldCheck className="w-4 h-4 text-emerald-500" />
                            </div>
                            
                            <div className="flex items-start gap-4 mb-4 text-zinc-400">
                                <MessageSquareQuote className="w-5 h-5 opacity-20" />
                                <div className="prose prose-invert prose-sm max-w-none text-zinc-300 whitespace-pre-line leading-relaxed">
                                    {summary}
                                </div>
                            </div>

                            <div className="flex items-center justify-between mt-6 pt-6 border-t border-zinc-800/50">
                                <div className="flex items-center gap-2">
                                    <div className="w-2 h-2 rounded-full bg-emerald-500" />
                                    <span className="text-[10px] font-black uppercase tracking-widest text-zinc-600">Generated by Gemini AI Engine</span>
                                </div>
                                <button 
                                    onClick={generateSummary}
                                    className="text-[10px] font-bold text-zinc-500 hover:text-blue-400 uppercase tracking-widest transition-colors"
                                >
                                    Regenerate Analysis
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {!summary && !isLoading && (
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 opacity-40">
                        <div className="p-4 bg-zinc-800/30 rounded-xl border border-dashed border-zinc-700">
                            <div className="w-8 h-1 bg-zinc-700 rounded mb-2" />
                            <div className="w-16 h-1 bg-zinc-700/50 rounded" />
                        </div>
                        <div className="p-4 bg-zinc-800/30 rounded-xl border border-dashed border-zinc-700">
                           <div className="w-8 h-1 bg-zinc-700 rounded mb-2" />
                           <div className="w-16 h-1 bg-zinc-700/50 rounded" />
                        </div>
                        <div className="p-4 bg-zinc-800/30 rounded-xl border border-dashed border-zinc-700">
                           <div className="w-8 h-1 bg-zinc-700 rounded mb-2" />
                           <div className="w-16 h-1 bg-zinc-700/50 rounded" />
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
